### ISSUE TITLE
Completely rename "Noto Serif Nyiakeng Puachue Hmong" to "Noto Serif NP Hmong"

### ISSUE THREAD

**Issue by twardoch** [notofonts/nyiakeng-puachue-hmong#1]
Font family names inside of fonts are limited to 32 chars, so internally the font has the name "Noto Serif Nyiakeng Puachue Hmo". This does not look good. 

I’d recommend to rename it to "Noto Serif NP Hmong". The "Nyiakeng Puachue" bit is less essential — and it’s similar to what we do with Noto Serif TC.

**Comment by twardoch** [comment]
OK, it’s a bit more complex — the Windows family name is `Noto Serif Hmong Nyiakeng` and the typographic family name is `Noto Serif Nyiakeng Puachue Hmong`, which is over the conventional limit. This will mean that the fonts will not appear in some apps. Such a long family name also causes various other problems.

**Comment by simoncozens** [comment]
I'm not sure how to handle this. The "external" name in fonts.google is Noto Serif Nyiakeng Puachue Hmong, and ideally we would like to keep it the same. But obviously this is very long. The postscript name and the family name are different, which is a problem, and ideally we would like to keep *them* the same too.

Perhaps internally it should all be "NP Hmong" as you suggest, with an external remapping for fonts.google.

**Comment by simoncozens** [comment]
This is now done, I think.
