### ISSUE TITLE
U+25CC DOTTED CIRCLE’s anchor point is off center

### ISSUE THREAD

**Issue by dscorbett** [notofonts/nyiakeng-puachue-hmong#3]
### Font
NotoSerifNPHmong-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/nyiakeng-puachue-hmong/releases/tag/NotoSerifNPHmong-v1.001
Date: 2022-09-15

### Font version
Version 1.001

### Issue
U+25CC DOTTED CIRCLE’s anchor point is off center. Marks are centered above letters, so they should be centered above the dotted circle.

### Character data
◌𞄱
U+25CC DOTTED CIRCLE
U+1E131 NYIAKENG PUACHUE HMONG TONE-M

### Screenshot
![◌𞄱](https://user-images.githubusercontent.com/1124347/190383127-655bf9b3-cd0c-4185-9d75-b80899db2f46.png)

**Comment by Mercury13** [comment]
Just unanchored. You need to add this anchor.
![image](https://user-images.githubusercontent.com/10164882/198851505-30caff6e-be4e-4f1e-883d-ec0b12f214b3.png)

**Comment by Mercury13** [comment]
Could you tell me how to edit those fonts?

**Comment by simoncozens** [comment]
You can use any font editor which understands the UFO format - Glyphs, FontLab, Robofont, MFEK, Runebender, etc.
